version: "3.8"

services:
  db:
    container_name: "db_users_tasks"
    image: "postgres:16.2-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "users_tasks"
      POSTGRES_PASSWORD: "users_tasks"
      POSTGRES_DB: "users_tasks"
